extends: airbnb
rules:
  max-len: ["error", 150]
  no-alert: 0
  no-path-concat: 0
  object-curly-spacing: 0
  react/no-multi-comp: 0
  react/prop-types: 0
  react/prefer-stateless-function: 0
  jsx-a11y/label-has-for: 0
env:
  browser: true
